// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlC-y13sR1rRKzcHvjdC2H-KlhflVpeWM',
    appId: '1:162508822733:web:5af5a4b48ee1eefa50f184',
    messagingSenderId: '162508822733',
    projectId: 'triplensproject',
    authDomain: 'triplensproject.firebaseapp.com',
    storageBucket: 'triplensproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOb03BBZqTtBeGibvzzlWnuxnaYvppWQM',
    appId: '1:162508822733:android:74b70e9ce40b047350f184',
    messagingSenderId: '162508822733',
    projectId: 'triplensproject',
    storageBucket: 'triplensproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5f4wLxPR37aFv3g3xr1jYUE1QP_RrPo',
    appId: '1:162508822733:ios:967de41c060b7c9850f184',
    messagingSenderId: '162508822733',
    projectId: 'triplensproject',
    storageBucket: 'triplensproject.firebasestorage.app',
    iosBundleId: 'com.example.triplenseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq5f4wLxPR37aFv3g3xr1jYUE1QP_RrPo',
    appId: '1:162508822733:ios:967de41c060b7c9850f184',
    messagingSenderId: '162508822733',
    projectId: 'triplensproject',
    storageBucket: 'triplensproject.firebasestorage.app',
    iosBundleId: 'com.example.triplenseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlC-y13sR1rRKzcHvjdC2H-KlhflVpeWM',
    appId: '1:162508822733:web:6d3dc8b993a1034350f184',
    messagingSenderId: '162508822733',
    projectId: 'triplensproject',
    authDomain: 'triplensproject.firebaseapp.com',
    storageBucket: 'triplensproject.firebasestorage.app',
  );
}
