# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUnPemEqe4rMP9SsyozFeVLndmkTUWOB
"""
import pandas as pd
import difflib

import mysql.connector

def get_metadata_from_db(landmark_id):
    conn = mysql.connector.connect(
        host='localhost',
        user='root',
        password='2468',
        database='tourism'
    )
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM places WHERE Landmark_ID = %s", (landmark_id,))
    result = cursor.fetchone()
    cursor.close()
    conn.close()
    return result


data_cat = ['ANC_02',
 'ANC_03',
 'ANC_04',
 'ANC_05',
 'Anc_01',
 'MOD_01',
 'MOD_02',
 'MOD_03',
 'MOD_04',
 'MOD_05',
 'NAT_01',
 'NAT_02',
 'NAT_03',
 'NAT_04',
 'NAT_05',
 'REL_01',
 'REL_02',
 'REL_03',
 'REL_04',
 'REL_05',
 'TMP_01',
 'TMP_02',
 'TMP_03',
 'TMP_04',
 'TMP_05']

import sys
import json
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from PIL import Image
import re
import google.generativeai as genai
from duckduckgo_search import DDGS



cnn_model = load_model("landmark_ID.keras")


#np.save("data_cat.npy", data_cat)

data_cat = np.load("data_cat.npy", allow_pickle=True)

  # ✅ This defines 'genai'

# Now you can configure it
genai.configure(api_key="AIzaSyBz_tKNj3JADjCraVLu-2pG_qjU4Hi1sU0")
import time
from duckduckgo_search import DDGS

def get_duckduckgo_image_url(query):
    with DDGS() as ddgs:
        time.sleep(2)  # Rate limiting: add delay
        results = ddgs.images(query, max_results=1)
        for r in results:
            return r["image"]


import json
import re

def get_landmark_metadata(image_path):
    model = genai.GenerativeModel("gemini-1.5-flash")
    image = Image.open(image_path)

    prompt = """
You are an expert landmark identifier. 
Only output valid pure JSON object, without Markdown blocks or explanations.
Format:
{
  "name": "Landmark Name",
  "category": "Category (Ancient, Modern, Nature, Religious, Temple)",
  "description": "Short description",
  "city": "City Name",
  "locationString": "Formatted location",
  "link_location": "Google Maps or equivalent location URL",
  "rating": "Estimated user rating out of 5 (e.g., 4.7)"
}
"""

    response = model.generate_content([prompt, image])
    result_text = response.text.strip()

    # Clean up extra "Metadata:" and markdown backticks
    result_text = re.sub(r"^Metadata:\s*", "", result_text, flags=re.IGNORECASE)
    result_text = result_text.replace("```json", "").replace("```", "").strip()

    # Extract valid JSON
    try:
        metadata_raw = json.loads(result_text)
    except Exception as e:
        print("Error parsing metadata JSON:", e)
        return {"error": "Failed to parse metadata."}

        # Normalize keys with proper casing (keep 'locationString' etc.)
    def normalize_key(key):
        return key.strip().replace(" ", "").replace("Locationstring", "locationString")

    # Updated key cleanup
    metadata = {}
    for key, value in metadata_raw.items():
        fixed_key = normalize_key(key)

        # Clean and parse rating safely
        if fixed_key == "rating":
            try:
                if isinstance(value, str):
                    value = float(re.sub(r"[^\d.]", "", value))  # Remove non-numeric chars
                elif isinstance(value, (int, float)):
                    value = float(value)
                else:
                    value = 0.0
            except:
                value = 0.0

        metadata[fixed_key] = value



    # Now optionally add image_url if needed
    if "name" in metadata:
        image_url = get_duckduckgo_image_url(metadata["name"])
        if image_url:
            metadata["image_url"] = image_url

    return metadata


import mysql.connector
import re

def insert_metadata_to_db(image_path):
    metadata = get_landmark_metadata(image_path)
    if "error" in metadata:
        return {"error": "Metadata generation failed."}

    name = metadata.get("name", "").strip().lower()

    # Connect to DB
    conn = mysql.connector.connect(
        host='localhost',
        user='root',
        password='2468',
        database='tourism'
    )
    cursor = conn.cursor(dictionary=True)

    # Check for existing landmark with the same name (case-insensitive)
    cursor.execute("SELECT * FROM places WHERE LOWER(name) = %s", (name,))
    existing = cursor.fetchone()

    if existing:
        metadata["Landmark_ID"] = existing["Landmark_ID"]
        metadata["note"] = "Duplicate found. Returning existing entry."
        cursor.close()
        conn.close()
        return metadata

    # Proceed to create new ID if not found
    category = metadata.get("category", "UNK").upper()
    prefix_map = {
        "ANCIENT": "ANC",
        "MODERN": "MOD",
        "NATURE": "NAT",
        "RELIGIOUS": "REL",
        "TEMPLE": "TMP"
    }
    prefix = prefix_map.get(category, "UNK")

    cursor.execute("SELECT Landmark_ID FROM places WHERE Landmark_ID LIKE %s", (f"{prefix}_%",))
    existing_ids = [row["Landmark_ID"] for row in cursor.fetchall()]
    numbers = [int(re.search(rf"{prefix}_(\d+)", lid).group(1)) for lid in existing_ids if re.search(rf"{prefix}_(\d+)", lid)]
    next_id_number = max(numbers) + 1 if numbers else 1
    new_id = f"{prefix}_{next_id_number:02d}"

    cursor.execute("""
        INSERT INTO places (Landmark_ID, name, category, description, city, locationString, link_location, image_url, rating)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        new_id,
        metadata.get("name"),
        category,
        metadata.get("description"),
        metadata.get("city"),
        metadata.get("locationString"),
        metadata.get("link_location"),
        metadata.get("image_url"),
        metadata.get("rating")
    ))

    conn.commit()
    cursor.close()
    conn.close()

    metadata["Landmark_ID"] = new_id
    return metadata


def recognize_landmark(image_path, model, data_cat, confidence_threshold=80):
    img_height, img_width = 224, 224
    image = tf.keras.utils.load_img(image_path, target_size=(img_height, img_width))
    img_array = tf.keras.utils.img_to_array(image)
    img_batch = tf.expand_dims(img_array, 0)

    predictions = model.predict(img_batch, verbose=0)
    scores = tf.nn.softmax(predictions[0])
    confidence = np.max(scores) * 100
    predicted_label = data_cat[np.argmax(scores)]

    result = {}

    if confidence < confidence_threshold:
        metadata = insert_metadata_to_db(image_path)
        result = metadata
    else:
        db_metadata = get_metadata_from_db(predicted_label)

        if db_metadata:
            result = {
                "Landmark_ID": db_metadata.get("Landmark_ID", ""),
                "name": db_metadata.get("name", ""),
                "description": db_metadata.get("description", ""),
                "link_location": db_metadata.get("link_location", ""),
                "image_url": db_metadata.get("image_url", "")
            }
        else:
            result = {
                "Landmark_ID": predicted_label,
                "note": "Metadata not found in database."
            }

    return result


# Run if script is executed directly
if __name__ == "__main__":
    if len(sys.argv) > 1:
        image_path = sys.argv[1]
        result = recognize_landmark(image_path, cnn_model, data_cat)
        print(json.dumps(result))
    else:
        print("No image path provided.")

        
#recognize_landmark(r"C:\Users\Dell G3\landmark-backend\oppo.jpg", cnn_model, data_cat, meta_data)
# Example call
#recognize_landmark(r"C:\Users\Dell G3\landmark-backend\oppo.jpg", cnn_model, data_cat)

#curl -X POST http://localhost:4000/predict -F "image=@\"C:\Users\Dell G3\landmark-backend\oppo.jpg\""




